# Generated by Django 5.1.3 on 2025-01-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('joining_date', models.DateField()),
                ('emp_id', models.CharField(max_length=10)),
            ],
        ),
    ]
